function fig = cameg_datapre()
% ___________________________________________________________________________
% CADSuM (Classification of AD Sufferers using Machine Learning)
%
% Copyright 2016 Cincinnati Children's Hospital Medical Center
% Reference 
% 
% 
% v1.0 Vahab Youssofzadeh 21/07/2016
% email: Vahab.Youssofzadeh@cchmc.org
% ___________________________________________________________________________
disp('cameg data prepration ...')
col = [0.8020 0.9072 0.4014];

h0 = figure('Color',[1 1 1], ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[450 250 390 210], ...
	'Tag','Main', ...
	'NumberTitle','off',...
	'Name','ToolBox : CA-MEG v.1', ...
	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 85 166 16], ...
	'String','Import data file', ...
	'CallBack','cameg_datapre_readdata');
h2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 60 166 16], ...
	'String','Import MRI file', ...
	'CallBack','cameg_datapre_readmri');
h3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 35 166 16], ...
	'String','Import surface file', ...
	'CallBack','cameg_datapre_readsurf');
h4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',col, ...
	'Position',[72 10 166 16], ...
	'String','Import mesh file', ...
	'CallBack','cameg_datapre_readmesh');
h5 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[16 110 280 36], ...
	'String','Data from Brainstorm toolbox', ...
	'Style','text', ...
	'Tag','StaticText5');
% h6 = uicontrol('Parent',h0, ...
% 	'Units','points', ...
% 	'BackgroundColor',col, ...
% 	'Position',[1 85 66 16], ...
% 	'String','Display image', ...
% 	'CallBack','cadsum_preprocess_disp');
% h7 = uicontrol('Parent',h0, ...
% 	'Units','points', ...
% 	'BackgroundColor',col, ...
% 	'Position',[1 60 66 16], ...
% 	'String','Check Reg', ...
% 	'CallBack','cadsum_preprocess_checkReg');
if nargout > 0, fig = h0; end
